### ISSUE TITLE
Scannit looks like has problems when using it in a tomcat 8 webapp

### ISSUE THREAD

**Issue by gionn** [hierynomus/scannit#10]
Something like:

```
scannit.getTypesAnnotatedWith(Protocol.class);
```

was returning empty results (snippet from overthere library) when using the library on the latest tomcat 8.0.26 with java 8, while it is working with the same webapp under tomcat 7.0.52 with java 8.

**Comment by hierynomus** [comment]
Hi Giovanni,

Is this with the 1.3.1 version of scannit, or the 1.4.0?

**Comment by Arnaud-Nauwynck** [comment]
Apparently, it occurs also in 1.4.0, and it is due to a leading "/" in tomcat-8 ClassLoader resource URIs

for example:
ask to scan "a.b.c"
the code in nl.javadude.scannit.reader.ClasspathReader.findURIs() calls
tomcat WebAppClassLoader.getResources("a/b/c")
which return a URI "<<tomcatDir>>/webapps/<<youWebApp>>/WEB-INF/lib/<<yourJar>>!a/b/c/"  
Then the code in scannit   ClasspathReader.findBaseURIs()  does  remove 5 chars (which is the number of chars from "a/b/c"    without leading "/" !) 
... so you erroneously get "<<tomcatDir>>/webapps/<<youWebApp>>/WEB-INF/lib/<<yourJar>>!a"  ... with an extra char!
see code:
`
public Set<URI> findBaseURIs(String prefix) {
        Set<URI> result = new HashSet<URI>();

        Set<URI> urIs = findURIs(prefix);
        String path = packagePrefixToPath(prefix);
        for (URI urI : urIs) {
            String schemeSpecificPart = urI.getSchemeSpecificPart();
            String based = schemeSpecificPart.substring(0, schemeSpecificPart.length() - path.length());
`

The patch to fix it seems obvious, you should remove leading "/"
` 
            String schemeSpecificPart = urI.getSchemeSpecificPart();
            if (schemeSpecificPart.endsWith("/")) {
                schemeSpecificPart = schemeSpecificPart.substring(0, schemeSpecificPart.length()-1);
            }
            String based = schemeSpecificPart.substring(0, schemeSpecificPart.length() - path.length());
`

Notice that when I tryed to compile, I got this:
`
$ gradle build
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve org.javassist:javassist:3.17.1-GA.
`

(I don't have access to maven central from behind firewall...)
Apparently, in build.graddle, you should simply add 
`
repositories {
        mavenLocal()
	mavenCentral()
}
`

**Comment by hierynomus** [comment]
Change from @zerikv merged and 1.4.1 released.
